### ISSUE TITLE
Not syncing

### ISSUE THREAD

**Issue by johanbluecreek** [fznply/rsync-save#2]
I do not get the files to sync. At the root of the project I placed the JSON file, where the field `remoteHost` has been set to a hostname that works (meaning `ssh name` logs me in without password), and `remotePath` is the absolute path on the remote machine, and `enable` is set to `true`. Still, on the remote server I get no ssh/rsync login attempts.

I tried the `rsync-save:toggle` as well, but it just greys out the whole atom window  and tells me it is alive, and I cannot get rid of it except for triggering `rsync-save:toggle` again. But the greyed out atom window is still responsive so I edit a file and save it, but no sync perform (again, no login attempts on the server).

**Comment by hevisko** [comment]
Same issue, I guess this is not working with the latest atoms or is a "broken" package? ;(

**Comment by fznply** [comment]
> I do not get the files to sync. At the root of the project I placed the JSON file, where the field `remoteHost` has been set to a hostname that works (meaning `ssh name` logs me in without password), and `remotePath` is the absolute path on the remote machine, and `enable` is set to `true`. Still, on the remote server I get no ssh/rsync login attempts.
> 
> I tried the `rsync-save:toggle` as well, but it just greys out the whole atom window and tells me it is alive, and I cannot get rid of it except for triggering `rsync-save:toggle` again. But the greyed out atom window is still responsive so I edit a file and save it, but no sync perform (again, no login attempts on the server).

I guess it is the version 0.9.7 <rsync-save> bug:  because it does not observe "File -> Add Project Folder" event .  

And also you should put the `.rsync_save.json` file in Project Root Folder.

Now i already fix this bug at the version 0.9.9. Please tell me if not work.

**Comment by fznply** [comment]
> Same issue, I guess this is not working with the latest atoms or is a "broken" package? ;(

I am so sorry about this issue. It bothers some developers so long. Now i have fixed this bug at the version 0.9.9. Please tell me if not work.
